language: python
python:

  - "3.6"

# command to install dependencies


install:
  - pip install Cython --install-option="--no-cython-compile" # needed for the gui testing, if testing will be used.
  - pip install -r requirements.txt


script:

  # Use a special key to trigger the testing mode of the program
  - python src/launch.py < testData.txt




